
services:
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "8002:8002"
    volumes:
      - ./backend/app:/app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo_user:dobleq3@mongo:27017/mantencion?authSource=admin
      - DB_NAME=mantencion
      - PORT=8002

  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: dobleq3

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"  # Puedes cambiar el puerto externo si lo deseas
    volumes:
      - grafana_data:/var/lib/grafana  # Persistencia de datos
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped
volumes:
  mongo_data:
  grafana_data:
